name: Boompvp
version: '${project.version}'
main: me.dlabaja.boompvp.Main
api-version: 1.18
authors: [ dlabaja ]
description: BoomPVP minigame

commands:
  boomkit:
    description: sets a boompvp kit
    usage: /boomkit [1-4]

  skipmap:
    description: skips a map
    usage: /skipmap (requires op)